# Numpy array and basics

In [14]:
import numpy as np
import time

### creating arrays from list

In [15]:
ary_1D = np.array([1,2,3])
print("1D array: ",ary_1D)

ary_2D = np.array([[1,2,3],[4,5,6]])
print("2D array: ",ary_2D)

1D array:  [1 2 3]
2D array:  [[1 2 3]
 [4 5 6]]


#### list vs numpy arrays 

In [16]:
py_list = [1,2,3]
print("Multiplication of python list: ",py_list*2)

np_array = np.array([1,3,4])
print("Multiplication of numpy arrays : ",np_array*2)

start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time ",time.time()-start)


start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time : ",time.time()-start)


Multiplication of python list:  [1, 2, 3, 1, 2, 3]
Multiplication of numpy arrays :  [2 6 8]

 List operation time  0.05200457572937012

 Numpy operation time :  0.0050046443939208984


### creating array from scratch


In [17]:
zeros = np.zeros((3,4))

print("zeros array:\n ",zeros)

ones = np.ones((3,3))
print("Ones arrays \n:",ones)


full = np.full((2,2),7)
print("Full array:\n",full)


random = np.random.random((3,3))
print("Random matrices : \n",random)

sequence = np.arange(0,10,2)
print("Sequence array\n",sequence)

zeros array:
  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones arrays 
: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Full array:
 [[7 7]
 [7 7]]
Random matrices : 
 [[0.70081019 0.09592365 0.42326093]
 [0.48687372 0.40136821 0.78599894]
 [0.76394536 0.88449302 0.53600445]]
Sequence array
 [0 2 4 6 8]


### Vector, Matrix and Tensor 


In [18]:
vector = np.array([1,2,4])
print("Vector: ",vector)

Matrix = np.array([[1,3],[2,3]])
print("Matrix: ",Matrix)

Tensor = np.array([[[1,2],[3,8]],
                   [[2,3],[9,8]]])
print("Tensor",Tensor)

Vector:  [1 2 4]
Matrix:  [[1 3]
 [2 3]]
Tensor [[[1 2]
  [3 8]]

 [[2 3]
  [9 8]]]


### Array Properties


In [19]:
arr = np.array([[1,2,3],
               [4,5,6]])
print("Shape of array",arr.shape) # The shape is a tuple that shows the number of elements along each axis

print("Dimension of array: ",arr.ndim) #The number of axes (dimensions) the array has.

print("Size",arr.size) # The total number of elements in the array.

print("DType",arr.dtype)


Shape of array (2, 3)
Dimension of array:  2
Size 6
DType int64


### Array Reshaping

In [24]:
arr = np.arange(12)
print("Original array",arr)

reshaped = arr.reshape((3,4))
print("Reshaped Array",reshaped)

flattened = reshaped.flatten() # flattens the array and Returns a copy
print("\n Flattened Array ", flattened)


raveled = reshaped.ravel() # Returns a view
print("\n raveled array ",raveled)

# Transpose
transpose = reshaped.T
print("\n Transposed Array: ",transpose)

# Difference between Flattened and Raveled 
flattened[0] = 999
print("\nAfter modifying flattened:")
print("flattened:", flattened)
print("reshaped:", reshaped) # Here you can see it doesn't modifies the Original array 



raveled[1] = 888
print("\nAfter modifying raveled:")
print("raveled:", raveled)
print("reshaped:", reshaped) # It modifies the Original array





Original array [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened Array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed Array:  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]

After modifying flattened:
flattened: [999   1   2   3   4   5   6   7   8   9  10  11]
reshaped: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

After modifying raveled:
raveled: [  0 888   2   3   4   5   6   7   8   9  10  11]
reshaped: [[  0 888   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]
